apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world-app
spec:
  selector:
    app: hello-world
  ports:
  - name: hello-world
    port: 80
    targetPort: 80
  type: ClusterIP
